### ISSUE TITLE
images don't get copied to public folder

### ISSUE THREAD

**Issue by imjared** [patronage/bubs-static#1]
as far as i can tell, images don't get copied to /public/img when gulp is running and they're added to /assets/img

to reproduce:
1. start gulp
2. open assets/img
3. move an image to this folder

**expected result:**
Per the watch task [here](https://github.com/jukingthestats/bubs-static/blob/4d35f732b0b60bb50d4f2faec7108a4268389a1e/gulpfile.js#L148), I'd expect the imagemin task to run

**actual result:**
nothing happens

**Comment by ccorda** [comment]
When I duplicate an image, the copy task catches it.  Closing out.
